version: "3.9"

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfiles/MySQL/Dockerfile
    restart: always
    container_name: MySQL_SBD
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      sbd_network:
        ipv4_address: 172.20.0.3

  postgres:
    image: postgres
    container_name: Postgres_SBD
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./Configs/Hard_Test/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    networks:
      sbd_network:
        ipv4_address: 172.20.0.2

  mariadb:
    build:
      context: .
      dockerfile: Dockerfiles/MariaDB/Dockerfile
    restart: always
    container_name: MariaDB_SBD
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sbdDatabase
    ports:
      - "3308:3306"
    volumes:
      - mariadb-volume:/var/lib/mysql:rw
    networks:
      sbd_network:
        ipv4_address: 172.20.0.4

  hammer-gui:
    image: tpcorg/hammerdb:latest-cloudtk
    restart: always
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8080:8080"
    depends_on:
      - mysql
      - postgres
      - mariadb
    volumes:
      - ./Scripts:/home/HammerDB-4.10/scripts/tcl-scripts
      - ./stats-logs:/exp-logs
    networks:
      sbd_network:
        ipv4_address: 172.20.0.5

volumes:
  mysql-volume:
    driver: local
  postgres-volume:
    driver: local
  mariadb-volume:
    driver: local

networks:
  sbd_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
