version: "3.9"

services:
  mysql:
    image: mysql:8.4
    restart: always
    container_name: MySQL_SBD
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./Configs/Hard_Test/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    networks:
      - sbd_network

  postgres:
    image: postgres
    container_name: postgres-sbd
    hostname: postgres-database
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - sbd_network
    environment:
      POSTGRES_PASSWORD: "1234"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./Configs/Hard_Test/postgresql.conf:/etc/postgresql/postgresql.conf:ro

  mariadb:
    image: mariadb:latest
    restart: always
    container_name: Mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sbdDatabase
    ports:
      - "3308:3306"
    volumes:
      - "./Configs/2nd test/my.cnf:/etc/mysql/my.cnf"
      # - "./Configs/3rd test/my.cnf:/etc/mysql/my.cnf"
    networks:
      - sbd_network

  hammer-gui:
    image: tpcorg/hammerdb:latest-cloudtk
    restart: always
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8080:8080"
    networks:
      - sbd_network
    depends_on:
      - mysql
      - postgres
      - mariadb
    volumes:
      - ./Scripts:/home/HammerDB-4.10/scripts/tcl-scripts
      - ./stats-logs:/exp-logs

volumes:
  mysql-volume:
    driver: local
  postgres-volume:
    driver: local

networks:
  sbd_network:
    driver: bridge
